[2025-01-23T04:38:37.310+0000] {processor.py:186} INFO - Started process (PID=1026452) to work on /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:38:37.311+0000] {processor.py:914} INFO - Processing file /root/airflow/dags/helloworld_dag.py for tasks to queue
[2025-01-23T04:38:37.314+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:38:37.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:38:37.319+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:38:37.317+0000] {dagbag.py:387} ERROR - Failed to import: /root/airflow/dags/helloworld_dag.py
Traceback (most recent call last):
  File "/root/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/airflow/dags/helloworld_dag.py", line 3, in <module>
    from airflow.modules.dag import DAG
ModuleNotFoundError: No module named 'airflow.modules'
[2025-01-23T04:38:37.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:38:37.343+0000] {processor.py:208} INFO - Processing /root/airflow/dags/helloworld_dag.py took 0.040 seconds
[2025-01-23T04:39:39.635+0000] {processor.py:186} INFO - Started process (PID=1026580) to work on /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:39:39.637+0000] {processor.py:914} INFO - Processing file /root/airflow/dags/helloworld_dag.py for tasks to queue
[2025-01-23T04:39:39.642+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:39:39.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:39:39.650+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:39:39.648+0000] {dagbag.py:387} ERROR - Failed to import: /root/airflow/dags/helloworld_dag.py
Traceback (most recent call last):
  File "/root/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/airflow/dags/helloworld_dag.py", line 3, in <module>
    from airflow.modules.dag import DAG
ModuleNotFoundError: No module named 'airflow.modules'
[2025-01-23T04:39:39.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:39:39.687+0000] {processor.py:208} INFO - Processing /root/airflow/dags/helloworld_dag.py took 0.062 seconds
[2025-01-23T04:40:13.122+0000] {processor.py:186} INFO - Started process (PID=1026618) to work on /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:40:13.124+0000] {processor.py:914} INFO - Processing file /root/airflow/dags/helloworld_dag.py for tasks to queue
[2025-01-23T04:40:13.129+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:40:13.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:40:13.138+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:40:13.135+0000] {dagbag.py:387} ERROR - Failed to import: /root/airflow/dags/helloworld_dag.py
Traceback (most recent call last):
  File "/root/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/airflow/dags/helloworld_dag.py", line 3, in <module>
    from airflow.modules.dag import DAG
ModuleNotFoundError: No module named 'airflow.modules'
[2025-01-23T04:40:13.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:40:13.175+0000] {processor.py:208} INFO - Processing /root/airflow/dags/helloworld_dag.py took 0.064 seconds
[2025-01-23T04:40:49.177+0000] {processor.py:186} INFO - Started process (PID=1026653) to work on /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:40:49.179+0000] {processor.py:914} INFO - Processing file /root/airflow/dags/helloworld_dag.py for tasks to queue
[2025-01-23T04:40:49.185+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:40:49.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:40:49.192+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:40:49.190+0000] {dagbag.py:387} ERROR - Failed to import: /root/airflow/dags/helloworld_dag.py
Traceback (most recent call last):
  File "/root/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/airflow/dags/helloworld_dag.py", line 3, in <module>
    from airflow.modules.dag import DAG
ModuleNotFoundError: No module named 'airflow.modules'
[2025-01-23T04:40:49.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:40:49.228+0000] {processor.py:208} INFO - Processing /root/airflow/dags/helloworld_dag.py took 0.064 seconds
[2025-01-23T04:41:24.203+0000] {processor.py:186} INFO - Started process (PID=1026688) to work on /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:41:24.205+0000] {processor.py:914} INFO - Processing file /root/airflow/dags/helloworld_dag.py for tasks to queue
[2025-01-23T04:41:24.209+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:41:24.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:41:24.216+0000] {logging_mixin.py:190} INFO - [2025-01-23T04:41:24.214+0000] {dagbag.py:387} ERROR - Failed to import: /root/airflow/dags/helloworld_dag.py
Traceback (most recent call last):
  File "/root/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/airflow/dags/helloworld_dag.py", line 3, in <module>
    from airflow.modules.dag import DAG
ModuleNotFoundError: No module named 'airflow.modules'
[2025-01-23T04:41:24.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /root/airflow/dags/helloworld_dag.py
[2025-01-23T04:41:24.248+0000] {processor.py:208} INFO - Processing /root/airflow/dags/helloworld_dag.py took 0.056 seconds
