[2025-03-27T20:05:32.456+0000] {processor.py:186} INFO - Started process (PID=1861672) to work on /root/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T20:05:32.457+0000] {processor.py:914} INFO - Processing file /root/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T20:05:32.460+0000] {logging_mixin.py:190} INFO - [2025-03-27T20:05:32.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /root/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T20:05:32.465+0000] {logging_mixin.py:190} INFO - [2025-03-27T20:05:32.464+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T20:05:32.465+0000] {logging_mixin.py:190} INFO - [2025-03-27T20:05:32.465+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T20:05:32.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /root/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T20:05:32.479+0000] {processor.py:208} INFO - Processing /root/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
