[2025-01-21T20:44:42.996+0000] {processor.py:186} INFO - Started process (PID=1007637) to work on /root/airflow/dags/helloworld_dag.py
[2025-01-21T20:44:42.997+0000] {processor.py:914} INFO - Processing file /root/airflow/dags/helloworld_dag.py for tasks to queue
[2025-01-21T20:44:43.000+0000] {logging_mixin.py:190} INFO - [2025-01-21T20:44:43.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /root/airflow/dags/helloworld_dag.py
[2025-01-21T20:44:43.009+0000] {logging_mixin.py:190} INFO - [2025-01-21T20:44:43.006+0000] {dagbag.py:387} ERROR - Failed to import: /root/airflow/dags/helloworld_dag.py
Traceback (most recent call last):
  File "/root/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/airflow/dags/helloworld_dag.py", line 3, in <module>
    from airflow.modules.dag import DAG
ModuleNotFoundError: No module named 'airflow.modules'
[2025-01-21T20:44:43.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /root/airflow/dags/helloworld_dag.py
[2025-01-21T20:44:43.044+0000] {processor.py:208} INFO - Processing /root/airflow/dags/helloworld_dag.py took 0.056 seconds
[2025-01-21T20:45:50.670+0000] {processor.py:186} INFO - Started process (PID=1007717) to work on /root/airflow/dags/helloworld_dag.py
[2025-01-21T20:45:50.671+0000] {processor.py:914} INFO - Processing file /root/airflow/dags/helloworld_dag.py for tasks to queue
[2025-01-21T20:45:50.676+0000] {logging_mixin.py:190} INFO - [2025-01-21T20:45:50.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /root/airflow/dags/helloworld_dag.py
[2025-01-21T20:45:50.683+0000] {logging_mixin.py:190} INFO - [2025-01-21T20:45:50.681+0000] {dagbag.py:387} ERROR - Failed to import: /root/airflow/dags/helloworld_dag.py
Traceback (most recent call last):
  File "/root/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/airflow/dags/helloworld_dag.py", line 3, in <module>
    from airflow.modules.dag import DAG
ModuleNotFoundError: No module named 'airflow.modules'
[2025-01-21T20:45:50.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /root/airflow/dags/helloworld_dag.py
[2025-01-21T20:45:50.729+0000] {processor.py:208} INFO - Processing /root/airflow/dags/helloworld_dag.py took 0.069 seconds
[2025-01-21T20:46:28.023+0000] {processor.py:186} INFO - Started process (PID=1007753) to work on /root/airflow/dags/helloworld_dag.py
[2025-01-21T20:46:28.026+0000] {processor.py:914} INFO - Processing file /root/airflow/dags/helloworld_dag.py for tasks to queue
[2025-01-21T20:46:28.030+0000] {logging_mixin.py:190} INFO - [2025-01-21T20:46:28.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /root/airflow/dags/helloworld_dag.py
[2025-01-21T20:46:28.037+0000] {logging_mixin.py:190} INFO - [2025-01-21T20:46:28.035+0000] {dagbag.py:387} ERROR - Failed to import: /root/airflow/dags/helloworld_dag.py
Traceback (most recent call last):
  File "/root/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/airflow/dags/helloworld_dag.py", line 3, in <module>
    from airflow.modules.dag import DAG
ModuleNotFoundError: No module named 'airflow.modules'
[2025-01-21T20:46:28.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /root/airflow/dags/helloworld_dag.py
[2025-01-21T20:46:28.086+0000] {processor.py:208} INFO - Processing /root/airflow/dags/helloworld_dag.py took 0.074 seconds
